export const IMG_CAPTIONS = [
  "🌙 *Juma Muborak!* \n\n🤲 *Alhamdulillah!* \n Bizni yana bir juma kuniga yetkazgan Allohga shukrlar bo‘lsin. \n\n 🕋 *La ilaha illallah!* \n Uning rahmati cheksiz, marhamati bitmas-tuganmas. \n\n 📖 *(Baqara: 152)* \n *\"Bas, Meni yod eting, Men ham sizni yod etaman!\"* \n\n 📿 *Allohning salomi, rahmati va barakoti \n Payg‘ambarimiz Muhammad Mustafo ﷺ ga bo‘lsin!* \n ✨ Ushbu muborak kun duolar, istaklar va ezgu niyatlar qabul bo‘ladigan fursat bo‘lsin.",
  "🌙 *Juma Muborak!* \n\n🤲 *Subhanallah!* \n Alloh bizga yana bir juma berdi. \n\n 🕋 *Allohu Akbar!* \n Uning qudrati va rahmati bilan yashaymiz. \n\n 📖 *(Ali Imron: 190)* \n *\"Osmonlar va yerning yaratilishida...\"* \n\n 📿 *Salovatlar bo‘lsin!* \n Muhammad Mustafo ﷺ ga Allohning rahmati yog‘ilsin. \n ✨ Juma kuni duolar qabul bo‘ladi, ibodatlaringizni ko‘paytiring.",
  "🌙 *Juma Muborak!* \n\n🤲 *Alhamdulillah!* \n Alloh bizni juma bilan barakali qildi. \n\n 🕋 *Alloh birdir!* \n Uning marhamati barchaga yetadi. \n\n 📖 *(Nahl: 18)* \n *\"Allohning ne‘matlarini sanab bo‘lmas.\"* \n\n 📿 *Salom bo‘lsin!* \n Payg‘ambarimiz Muhammad Mustafo ﷺ ga. \n ✨ Bu kunni ibodat va yaxshilik bilan o‘tkazing.",
  "🌙 *Juma Muborak!* \n\n🤲 *Subhanallah!* \n Allohning rahmati bilan juma keldi. \n\n 🕋 *La ilaha illallah!* \n Uning rahmati bizni qamrab oladi. \n\n 📖 *(Furqon: 62)* \n *\"U kechayu kunduzni yaratdi...\"* \n\n 📿 *Baraka bo‘lsin!* \n Muhammad Mustafo ﷺ ga salovatlar ayting. \n ✨ Juma – duo va rahmat kuni, fursatni qo‘ldan boy bermang.",
  "🌙 *Juma Muborak!* \n\n🤲 *Alhamdulillah!* \n Allohning rahmati bilan juma keldi. \n\n 🕌 *Allohu Akbar!* \n Uning ne‘matlari son-sanoqsiz. \n\n 📖 *(Juma: 9)* \n *\"Namozga shoshiling!\"* \n\n 📿 *Salovatlar!* \n Muhammad Mustafo ﷺ ga Allohning barakasi bo‘lsin. \n ✨ Bu kunni yaxshi amallar bilan bezang.",
  "🌙 *Juma Muborak!* \n\n🤲 *Subhanallah!* \n Alloh bizni juma bilan siyladi. \n\n 🕋 *La ilaha illallah!* \n Uning rahmati abadiy. \n\n 📖 *(Ankabut: 45)* \n *\"Namozni to‘kis ado eting...\"* \n\n 📿 *Salomlar bo‘lsin!* \n Payg‘ambarimiz Muhammad Mustafo ﷺ ga. \n📿 Juma kuni – duolar qabul bo‘ladigan vaqt.",
  "🌙 *Juma Muborak!* \n\n🤲 *Alhamdulillah!* \n Allohga shukrlar ki, juma keldi. \n\n 🕋 *Alloh birdir!* \n Uning marhamati bizni himoya qiladi. \n\n 📖 *(Hud: 6)* \n *\"Yerdagi har bir jon Uning rizqidadir.\"* \n\n 📿 *Barakalar!* \n Muhammad Mustafo ﷺ ga salovat ayting. \n ✨ Juma – yaxshilik va ibodat kuni.",
  "🌙 *Juma Muborak!* \n\n🤲 *Subhanallah!* \n Allohning rahmati bilan juma keldi. \n\n 🕋 *Allohu Akbar!* \n Uning qudrati hamma narsani qamrab oladi. \n\n 📖 *(Qaf: 38)* \n *\"Osmonlarni og‘riqsiz yaratdik...\"* \n\n 📿 *Salovatlar!* \n Payg‘ambarimiz Muhammad Mustafo ﷺ ga. \n ✨ Bu kunni duo va ezgu niyatlar bilan o‘tkazing.",
  "🌙 *Juma Muborak!* \n\n🤲 *Alhamdulillah!* \n Alloh bizni juma bilan xursand qildi. \n\n 🕋 *La ilaha illallah!* \n Uning rahmati cheksizdir. \n\n 📖 *(Zumar: 53)* \n *\"Allohning rahmatidan umidingizni uzmang!\"* \n\n 📿 *Salomlar!* \n Muhammad Mustafo ﷺ ga baraka bo‘lsin. \n ✨ Juma – rahmat va mag‘firat kuni.",
  "🌙 *Juma Muborak!* \n\n🤲 *Subhanallah!* \n Alloh bizga juma ne‘matini berdi. \n\n 🕌 *Alloh birdir!* \n Uning marhamati bilan yashaymiz. \n\n 📖 *(Tawba: 71)* \n *\"Mo‘minlar bir-biriga yordam beradi...\"* \n\n 📿 *Salovatlar!* \n Payg‘ambarimiz Muhammad Mustafo ﷺ ga. \n ✨ Bu kunni ibodat bilan o‘tkazib, duolar qiling."
]